org: ludde

service: quiztopia-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1


  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/quiztopia




functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  register: 
    handler: functions/Register/index.handler
    events:
      - httpApi:
          path: /register
          method: post
  
  login:
    handler: functions/Login/index.handler
    events:
      - httpApi:
         path: /login
         method: post